version: '2'
services: 
    go: 
        build: docker/golang
        image: go:1.7.4
    consul:
        image: consul
        container_name: consul
        ports:
           - "8500:8500"
        network_mode: 'host'
    fabio:
        build: ./docker/fabio
        image: fabio:1.3.5
        container_name: fabio
        ports: 
           - "80:80"
           - "9998:9998"
        depends_on:
           - consul
        network_mode: 'host'
        restart: always
    python:
        build: ./docker/simpleHTTPServer
        container_name: http8080
        ports:
            - "8080:8080"
        network_mode: 'host'
